### ISSUE TITLE
modal transition on getting back to menu is broken on iOS5

### ISSUE THREAD

**Issue by steipete** [Split82/HMGLTransitions#3]
Pretty great stuff - just letting you know that they changed sth in the new iOS that breaks the second animation (when you click on close to get back)

**Comment by Split82** [comment]
Thank you very much. I'm gonna chech it out.

**Comment by GMR42** [comment]
Hi,

the parentViewController property changed in iOS 5 to presentingViewController

so in HGMLTransition:
        self.newController = modalViewController.parentViewController is now nil

I think this should fix it:

```
if ([modalViewController respondsToSelector:@selector(presentingViewController)])
    self.newController = modalViewController.presentingViewController;
else
    self.newController = modalViewController.parentViewController;
```

HTH and thank you for sharing this 
Gareth

**Comment by steipete** [comment]
Great! Works again - I've sent you a pull request with the fix.
